spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cohort26
    username: postgres
    password: root
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
#logging:
#  file:
#    name: application.log
#  level:
#    root: info
